### ISSUE TITLE
Skip XQuartz

### ISSUE THREAD

**Issue by Gcenx** [dasmy/macos-crossover-cloud-build#7]
https://github.com/dasmy/macos-crossover-cloud-build/blob/bb3c6797ddc0cd2b2dc035567638b4e8a2c7a692/.github/workflows/build_monolithic.yml#L50

As wine32on64 doesn’t support this anyway you’d be better served avoiding XQuartz for the entire build.

**Comment by dasmy** [comment]
Hmm... - after removing XQuartz (I think this is related at least. - Due to the large roundtrip times I am doing numerous changes at once...), the wine64 configure step complains about more missing libs: Comparing https://github.com/dasmy/macos-crossover-cloud-build/runs/2222329863 and https://github.com/dasmy/macos-crossover-cloud-build/runs/2225597460, the following additional messages appeared:

> configure: WARNING: libxrender 64-bit development files not found, XRender won't be supported.
>
> configure: libxcursor 64-bit development files not found, the Xcursor extension won't be supported.
> configure: WARNING: No OpenGL library found on this system.
> configure: libxi 64-bit development files not found, the Xinput extension won't be supported.
> OpenGL and Direct3D won't be supported.
> configure: XShm 64-bit development files not found, X Shared Memory won't be supported.
> configure: XShape 64-bit development files not found, XShape won't be supported.
> configure: libXxf86vm 64-bit development files not found, XFree86 Vidmode won't be supported.
> configure: libxrandr 64-bit development files not found, XRandr won't be supported.
> configure: libxfixes 64-bit development files not found, Xfixes won't be supported.
> configure: libxinerama 64-bit development files not found, multi-monitor setups won't be supported.
> configure: libxcomposite 64-bit development files not found, Xcomposite won't be supported.
> configure: libGLU 64-bit development files not found, GLU won't be supported.
> configure: libOSMesa 64-bit development files not found (or too old), OpenGL rendering in bitmaps won't be supported.

Doesn't that sound problematic or should I just add `--without-x` here as well? No OpenGL and Direct3D sounds a bit dangerous problematic :-)

**Comment by Gcenx** [comment]
Just adding `--without-x` will silence all of those complains as they’re all related to X11.

The only reason I’d added XQuartz to the staging workflow was to ensure the X11 stuff would still build on macOS, as the primary display driver is macDriver (winemac.drv) it’s not a requirement and CodeWeavers don’t plan on fixing it for 32on64.

**Comment by dasmy** [comment]
Understood, removed references to X11 with https://github.com/dasmy/macos-crossover-cloud-build/commit/b1558a89a87f8892e0afacf801f6cc36ab884b8e .
